// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

void init({required String baseUrl}) =>
    RustLib.instance.api.crateFfiBridgeInit(baseUrl: baseUrl);

FfiAuthConfig getAuthConfig() =>
    RustLib.instance.api.crateFfiBridgeGetAuthConfig();

FfiUserAndToken login({required String username, required String password}) =>
    RustLib.instance.api.crateFfiBridgeLogin(
      username: username,
      password: password,
    );

FfiUser getCurrentUser() => RustLib.instance.api.crateFfiBridgeGetCurrentUser();

void logout() => RustLib.instance.api.crateFfiBridgeLogout();

FfiUser getProfile() => RustLib.instance.api.crateFfiBridgeGetProfile();

FfiUser updateProfile({String? displayName, String? imageUrl}) => RustLib
    .instance
    .api
    .crateFfiBridgeUpdateProfile(displayName: displayName, imageUrl: imageUrl);

FfiChatListResponse listChats({BigInt? page, BigInt? pageSize}) => RustLib
    .instance
    .api
    .crateFfiBridgeListChats(page: page, pageSize: pageSize);

FfiChat createChat({
  String? title,
  required String modelProvider,
  required String modelId,
}) => RustLib.instance.api.crateFfiBridgeCreateChat(
  title: title,
  modelProvider: modelProvider,
  modelId: modelId,
);

FfiChatWithMessages getChat({required String chatId}) =>
    RustLib.instance.api.crateFfiBridgeGetChat(chatId: chatId);

FfiChat updateChat({required String chatId, String? title}) =>
    RustLib.instance.api.crateFfiBridgeUpdateChat(chatId: chatId, title: title);

void deleteChat({required String chatId}) =>
    RustLib.instance.api.crateFfiBridgeDeleteChat(chatId: chatId);

List<FfiChatChunk> streamChat({
  required String chatId,
  required String message,
  required String modelProvider,
  required String modelId,
}) => RustLib.instance.api.crateFfiBridgeStreamChat(
  chatId: chatId,
  message: message,
  modelProvider: modelProvider,
  modelId: modelId,
);
