// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

class FfiAuthConfig {
  final bool oidcEnabled;

  const FfiAuthConfig({required this.oidcEnabled});

  @override
  int get hashCode => oidcEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiAuthConfig &&
          runtimeType == other.runtimeType &&
          oidcEnabled == other.oidcEnabled;
}

class FfiChat {
  final String id;
  final String userId;
  final String title;
  final String modelProvider;
  final String modelId;
  final String createdAt;
  final String updatedAt;

  const FfiChat({
    required this.id,
    required this.userId,
    required this.title,
    required this.modelProvider,
    required this.modelId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      title.hashCode ^
      modelProvider.hashCode ^
      modelId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiChat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          title == other.title &&
          modelProvider == other.modelProvider &&
          modelId == other.modelId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class FfiChatChunk {
  final String delta;
  final bool done;

  const FfiChatChunk({required this.delta, required this.done});

  @override
  int get hashCode => delta.hashCode ^ done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiChatChunk &&
          runtimeType == other.runtimeType &&
          delta == other.delta &&
          done == other.done;
}

class FfiChatListResponse {
  final List<FfiChat> data;
  final BigInt total;

  const FfiChatListResponse({required this.data, required this.total});

  @override
  int get hashCode => data.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiChatListResponse &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          total == other.total;
}

class FfiChatWithMessages {
  final FfiChat chat;
  final List<FfiMessage> messages;

  const FfiChatWithMessages({required this.chat, required this.messages});

  @override
  int get hashCode => chat.hashCode ^ messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiChatWithMessages &&
          runtimeType == other.runtimeType &&
          chat == other.chat &&
          messages == other.messages;
}

@freezed
sealed class FfiError with _$FfiError implements FrbException {
  const FfiError._();

  const factory FfiError.network(String field0) = FfiError_Network;
  const factory FfiError.auth(String field0) = FfiError_Auth;
  const factory FfiError.notFound(String field0) = FfiError_NotFound;
  const factory FfiError.server(String field0) = FfiError_Server;
  const factory FfiError.unknown(String field0) = FfiError_Unknown;
}

class FfiMessage {
  final String id;
  final String chatId;
  final String role;
  final String content;
  final String? metadata;
  final String? parentMessageId;
  final int sequenceNumber;
  final String createdAt;
  final int? tokensUsed;
  final String? modelUsed;

  const FfiMessage({
    required this.id,
    required this.chatId,
    required this.role,
    required this.content,
    this.metadata,
    this.parentMessageId,
    required this.sequenceNumber,
    required this.createdAt,
    this.tokensUsed,
    this.modelUsed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      chatId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      metadata.hashCode ^
      parentMessageId.hashCode ^
      sequenceNumber.hashCode ^
      createdAt.hashCode ^
      tokensUsed.hashCode ^
      modelUsed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          chatId == other.chatId &&
          role == other.role &&
          content == other.content &&
          metadata == other.metadata &&
          parentMessageId == other.parentMessageId &&
          sequenceNumber == other.sequenceNumber &&
          createdAt == other.createdAt &&
          tokensUsed == other.tokensUsed &&
          modelUsed == other.modelUsed;
}

class FfiUser {
  final String id;
  final String email;
  final bool? emailVerified;
  final String? name;
  final String? username;
  final String? avatarUrl;
  final List<String> roles;

  const FfiUser({
    required this.id,
    required this.email,
    this.emailVerified,
    this.name,
    this.username,
    this.avatarUrl,
    required this.roles,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      email.hashCode ^
      emailVerified.hashCode ^
      name.hashCode ^
      username.hashCode ^
      avatarUrl.hashCode ^
      roles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiUser &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email &&
          emailVerified == other.emailVerified &&
          name == other.name &&
          username == other.username &&
          avatarUrl == other.avatarUrl &&
          roles == other.roles;
}

class FfiUserAndToken {
  final FfiUser user;
  final String token;
  final PlatformInt64 expiresAt;

  const FfiUserAndToken({
    required this.user,
    required this.token,
    required this.expiresAt,
  });

  @override
  int get hashCode => user.hashCode ^ token.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiUserAndToken &&
          runtimeType == other.runtimeType &&
          user == other.user &&
          token == other.token &&
          expiresAt == other.expiresAt;
}
