// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'ffi/bridge.dart';
import 'ffi/types.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -428138599;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 't3chat_core',
        ioDirectory: 'native/t3chat_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  FfiChat crateFfiBridgeCreateChat({
    String? title,
    required String modelProvider,
    required String modelId,
  });

  void crateFfiBridgeDeleteChat({required String chatId});

  FfiAuthConfig crateFfiBridgeGetAuthConfig();

  FfiChatWithMessages crateFfiBridgeGetChat({required String chatId});

  FfiUser crateFfiBridgeGetCurrentUser();

  FfiUser crateFfiBridgeGetProfile();

  void crateFfiBridgeInit({required String baseUrl});

  FfiChatListResponse crateFfiBridgeListChats({BigInt? page, BigInt? pageSize});

  FfiUserAndToken crateFfiBridgeLogin({
    required String username,
    required String password,
  });

  void crateFfiBridgeLogout();

  void crateFfiBridgeSetToken({required String token});

  List<FfiChatChunk> crateFfiBridgeStreamChat({
    required String chatId,
    required String message,
    required String modelProvider,
    required String modelId,
  });

  FfiChat crateFfiBridgeUpdateChat({required String chatId, String? title});

  FfiUser crateFfiBridgeUpdateProfile({String? displayName, String? imageUrl});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  FfiChat crateFfiBridgeCreateChat({
    String? title,
    required String modelProvider,
    required String modelId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(title, serializer);
          sse_encode_String(modelProvider, serializer);
          sse_encode_String(modelId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_chat,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeCreateChatConstMeta,
        argValues: [title, modelProvider, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeCreateChatConstMeta => const TaskConstMeta(
    debugName: 'create_chat',
    argNames: ['title', 'modelProvider', 'modelId'],
  );

  @override
  void crateFfiBridgeDeleteChat({required String chatId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chatId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeDeleteChatConstMeta,
        argValues: [chatId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeDeleteChatConstMeta =>
      const TaskConstMeta(debugName: 'delete_chat', argNames: ['chatId']);

  @override
  FfiAuthConfig crateFfiBridgeGetAuthConfig() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_auth_config,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeGetAuthConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetAuthConfigConstMeta =>
      const TaskConstMeta(debugName: 'get_auth_config', argNames: []);

  @override
  FfiChatWithMessages crateFfiBridgeGetChat({required String chatId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chatId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_chat_with_messages,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeGetChatConstMeta,
        argValues: [chatId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetChatConstMeta =>
      const TaskConstMeta(debugName: 'get_chat', argNames: ['chatId']);

  @override
  FfiUser crateFfiBridgeGetCurrentUser() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_user,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeGetCurrentUserConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetCurrentUserConstMeta =>
      const TaskConstMeta(debugName: 'get_current_user', argNames: []);

  @override
  FfiUser crateFfiBridgeGetProfile() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_user,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeGetProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeGetProfileConstMeta =>
      const TaskConstMeta(debugName: 'get_profile', argNames: []);

  @override
  void crateFfiBridgeInit({required String baseUrl}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeInitConstMeta,
        argValues: [baseUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeInitConstMeta =>
      const TaskConstMeta(debugName: 'init', argNames: ['baseUrl']);

  @override
  FfiChatListResponse crateFfiBridgeListChats({
    BigInt? page,
    BigInt? pageSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_64(page, serializer);
          sse_encode_opt_box_autoadd_u_64(pageSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_chat_list_response,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeListChatsConstMeta,
        argValues: [page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeListChatsConstMeta => const TaskConstMeta(
    debugName: 'list_chats',
    argNames: ['page', 'pageSize'],
  );

  @override
  FfiUserAndToken crateFfiBridgeLogin({
    required String username,
    required String password,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_user_and_token,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeLoginConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeLoginConstMeta => const TaskConstMeta(
    debugName: 'login',
    argNames: ['username', 'password'],
  );

  @override
  void crateFfiBridgeLogout() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeLogoutConstMeta =>
      const TaskConstMeta(debugName: 'logout', argNames: []);

  @override
  void crateFfiBridgeSetToken({required String token}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeSetTokenConstMeta,
        argValues: [token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeSetTokenConstMeta =>
      const TaskConstMeta(debugName: 'set_token', argNames: ['token']);

  @override
  List<FfiChatChunk> crateFfiBridgeStreamChat({
    required String chatId,
    required String message,
    required String modelProvider,
    required String modelId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chatId, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(modelProvider, serializer);
          sse_encode_String(modelId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ffi_chat_chunk,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeStreamChatConstMeta,
        argValues: [chatId, message, modelProvider, modelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeStreamChatConstMeta => const TaskConstMeta(
    debugName: 'stream_chat',
    argNames: ['chatId', 'message', 'modelProvider', 'modelId'],
  );

  @override
  FfiChat crateFfiBridgeUpdateChat({required String chatId, String? title}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(chatId, serializer);
          sse_encode_opt_String(title, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_chat,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeUpdateChatConstMeta,
        argValues: [chatId, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeUpdateChatConstMeta => const TaskConstMeta(
    debugName: 'update_chat',
    argNames: ['chatId', 'title'],
  );

  @override
  FfiUser crateFfiBridgeUpdateProfile({String? displayName, String? imageUrl}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(displayName, serializer);
          sse_encode_opt_String(imageUrl, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_user,
          decodeErrorData: sse_decode_ffi_error,
        ),
        constMeta: kCrateFfiBridgeUpdateProfileConstMeta,
        argValues: [displayName, imageUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFfiBridgeUpdateProfileConstMeta =>
      const TaskConstMeta(
        debugName: 'update_profile',
        argNames: ['displayName', 'imageUrl'],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  FfiAuthConfig dco_decode_ffi_auth_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FfiAuthConfig(oidcEnabled: dco_decode_bool(arr[0]));
  }

  @protected
  FfiChat dco_decode_ffi_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FfiChat(
      id: dco_decode_String(arr[0]),
      userId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      modelProvider: dco_decode_String(arr[3]),
      modelId: dco_decode_String(arr[4]),
      createdAt: dco_decode_String(arr[5]),
      updatedAt: dco_decode_String(arr[6]),
    );
  }

  @protected
  FfiChatChunk dco_decode_ffi_chat_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiChatChunk(
      delta: dco_decode_String(arr[0]),
      done: dco_decode_bool(arr[1]),
    );
  }

  @protected
  FfiChatListResponse dco_decode_ffi_chat_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiChatListResponse(
      data: dco_decode_list_ffi_chat(arr[0]),
      total: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  FfiChatWithMessages dco_decode_ffi_chat_with_messages(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiChatWithMessages(
      chat: dco_decode_ffi_chat(arr[0]),
      messages: dco_decode_list_ffi_message(arr[1]),
    );
  }

  @protected
  FfiError dco_decode_ffi_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FfiError_Network(dco_decode_String(raw[1]));
      case 1:
        return FfiError_Auth(dco_decode_String(raw[1]));
      case 2:
        return FfiError_NotFound(dco_decode_String(raw[1]));
      case 3:
        return FfiError_Server(dco_decode_String(raw[1]));
      case 4:
        return FfiError_Unknown(dco_decode_String(raw[1]));
      default:
        throw Exception('unreachable');
    }
  }

  @protected
  FfiMessage dco_decode_ffi_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return FfiMessage(
      id: dco_decode_String(arr[0]),
      chatId: dco_decode_String(arr[1]),
      role: dco_decode_String(arr[2]),
      content: dco_decode_String(arr[3]),
      metadata: dco_decode_opt_String(arr[4]),
      parentMessageId: dco_decode_opt_String(arr[5]),
      sequenceNumber: dco_decode_i_32(arr[6]),
      createdAt: dco_decode_String(arr[7]),
      tokensUsed: dco_decode_opt_box_autoadd_i_32(arr[8]),
      modelUsed: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  FfiUser dco_decode_ffi_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FfiUser(
      id: dco_decode_String(arr[0]),
      email: dco_decode_String(arr[1]),
      emailVerified: dco_decode_opt_box_autoadd_bool(arr[2]),
      name: dco_decode_opt_String(arr[3]),
      username: dco_decode_opt_String(arr[4]),
      avatarUrl: dco_decode_opt_String(arr[5]),
      roles: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  FfiUserAndToken dco_decode_ffi_user_and_token(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiUserAndToken(
      user: dco_decode_ffi_user(arr[0]),
      token: dco_decode_String(arr[1]),
      expiresAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FfiChat> dco_decode_list_ffi_chat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_chat).toList();
  }

  @protected
  List<FfiChatChunk> dco_decode_list_ffi_chat_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_chat_chunk).toList();
  }

  @protected
  List<FfiMessage> dco_decode_list_ffi_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_message).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  FfiAuthConfig sse_decode_ffi_auth_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_oidcEnabled = sse_decode_bool(deserializer);
    return FfiAuthConfig(oidcEnabled: var_oidcEnabled);
  }

  @protected
  FfiChat sse_decode_ffi_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_modelProvider = sse_decode_String(deserializer);
    var var_modelId = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return FfiChat(
      id: var_id,
      userId: var_userId,
      title: var_title,
      modelProvider: var_modelProvider,
      modelId: var_modelId,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  FfiChatChunk sse_decode_ffi_chat_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_delta = sse_decode_String(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return FfiChatChunk(delta: var_delta, done: var_done);
  }

  @protected
  FfiChatListResponse sse_decode_ffi_chat_list_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_ffi_chat(deserializer);
    var var_total = sse_decode_u_64(deserializer);
    return FfiChatListResponse(data: var_data, total: var_total);
  }

  @protected
  FfiChatWithMessages sse_decode_ffi_chat_with_messages(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chat = sse_decode_ffi_chat(deserializer);
    var var_messages = sse_decode_list_ffi_message(deserializer);
    return FfiChatWithMessages(chat: var_chat, messages: var_messages);
  }

  @protected
  FfiError sse_decode_ffi_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return FfiError_Network(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return FfiError_Auth(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return FfiError_NotFound(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return FfiError_Server(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return FfiError_Unknown(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  FfiMessage sse_decode_ffi_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_chatId = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_metadata = sse_decode_opt_String(deserializer);
    var var_parentMessageId = sse_decode_opt_String(deserializer);
    var var_sequenceNumber = sse_decode_i_32(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_tokensUsed = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_modelUsed = sse_decode_opt_String(deserializer);
    return FfiMessage(
      id: var_id,
      chatId: var_chatId,
      role: var_role,
      content: var_content,
      metadata: var_metadata,
      parentMessageId: var_parentMessageId,
      sequenceNumber: var_sequenceNumber,
      createdAt: var_createdAt,
      tokensUsed: var_tokensUsed,
      modelUsed: var_modelUsed,
    );
  }

  @protected
  FfiUser sse_decode_ffi_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_emailVerified = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_username = sse_decode_opt_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    var var_roles = sse_decode_list_String(deserializer);
    return FfiUser(
      id: var_id,
      email: var_email,
      emailVerified: var_emailVerified,
      name: var_name,
      username: var_username,
      avatarUrl: var_avatarUrl,
      roles: var_roles,
    );
  }

  @protected
  FfiUserAndToken sse_decode_ffi_user_and_token(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_user = sse_decode_ffi_user(deserializer);
    var var_token = sse_decode_String(deserializer);
    var var_expiresAt = sse_decode_i_64(deserializer);
    return FfiUserAndToken(
      user: var_user,
      token: var_token,
      expiresAt: var_expiresAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiChat> sse_decode_list_ffi_chat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiChat>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_chat(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiChatChunk> sse_decode_list_ffi_chat_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiChatChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_chat_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiMessage> sse_decode_list_ffi_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_message(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_ffi_auth_config(
    FfiAuthConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.oidcEnabled, serializer);
  }

  @protected
  void sse_encode_ffi_chat(FfiChat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.modelProvider, serializer);
    sse_encode_String(self.modelId, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_ffi_chat_chunk(FfiChatChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.delta, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_ffi_chat_list_response(
    FfiChatListResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_ffi_chat(self.data, serializer);
    sse_encode_u_64(self.total, serializer);
  }

  @protected
  void sse_encode_ffi_chat_with_messages(
    FfiChatWithMessages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_chat(self.chat, serializer);
    sse_encode_list_ffi_message(self.messages, serializer);
  }

  @protected
  void sse_encode_ffi_error(FfiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FfiError_Network(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case FfiError_Auth(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case FfiError_NotFound(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case FfiError_Server(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case FfiError_Unknown(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_ffi_message(FfiMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.chatId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.metadata, serializer);
    sse_encode_opt_String(self.parentMessageId, serializer);
    sse_encode_i_32(self.sequenceNumber, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_box_autoadd_i_32(self.tokensUsed, serializer);
    sse_encode_opt_String(self.modelUsed, serializer);
  }

  @protected
  void sse_encode_ffi_user(FfiUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_opt_box_autoadd_bool(self.emailVerified, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.username, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
    sse_encode_list_String(self.roles, serializer);
  }

  @protected
  void sse_encode_ffi_user_and_token(
    FfiUserAndToken self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_user(self.user, serializer);
    sse_encode_String(self.token, serializer);
    sse_encode_i_64(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_chat(List<FfiChat> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_chat(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_chat_chunk(
    List<FfiChatChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_chat_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_message(
    List<FfiMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
