// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi/bridge.dart';
import 'ffi/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  FfiAuthConfig dco_decode_ffi_auth_config(dynamic raw);

  @protected
  FfiChat dco_decode_ffi_chat(dynamic raw);

  @protected
  FfiChatChunk dco_decode_ffi_chat_chunk(dynamic raw);

  @protected
  FfiChatListResponse dco_decode_ffi_chat_list_response(dynamic raw);

  @protected
  FfiChatWithMessages dco_decode_ffi_chat_with_messages(dynamic raw);

  @protected
  FfiError dco_decode_ffi_error(dynamic raw);

  @protected
  FfiMessage dco_decode_ffi_message(dynamic raw);

  @protected
  FfiUser dco_decode_ffi_user(dynamic raw);

  @protected
  FfiUserAndToken dco_decode_ffi_user_and_token(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiChat> dco_decode_list_ffi_chat(dynamic raw);

  @protected
  List<FfiChatChunk> dco_decode_list_ffi_chat_chunk(dynamic raw);

  @protected
  List<FfiMessage> dco_decode_list_ffi_message(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  FfiAuthConfig sse_decode_ffi_auth_config(SseDeserializer deserializer);

  @protected
  FfiChat sse_decode_ffi_chat(SseDeserializer deserializer);

  @protected
  FfiChatChunk sse_decode_ffi_chat_chunk(SseDeserializer deserializer);

  @protected
  FfiChatListResponse sse_decode_ffi_chat_list_response(
    SseDeserializer deserializer,
  );

  @protected
  FfiChatWithMessages sse_decode_ffi_chat_with_messages(
    SseDeserializer deserializer,
  );

  @protected
  FfiError sse_decode_ffi_error(SseDeserializer deserializer);

  @protected
  FfiMessage sse_decode_ffi_message(SseDeserializer deserializer);

  @protected
  FfiUser sse_decode_ffi_user(SseDeserializer deserializer);

  @protected
  FfiUserAndToken sse_decode_ffi_user_and_token(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiChat> sse_decode_list_ffi_chat(SseDeserializer deserializer);

  @protected
  List<FfiChatChunk> sse_decode_list_ffi_chat_chunk(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiMessage> sse_decode_list_ffi_message(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_auth_config(FfiAuthConfig self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_chat(FfiChat self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_chat_chunk(FfiChatChunk self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_chat_list_response(
    FfiChatListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_chat_with_messages(
    FfiChatWithMessages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_error(FfiError self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_message(FfiMessage self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_user(FfiUser self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_user_and_token(
    FfiUserAndToken self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_chat(List<FfiChat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_chat_chunk(
    List<FfiChatChunk> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_message(
    List<FfiMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
